### ISSUE TITLE
__getitem__() of SparseDataset doesn't work with scipy 1.3.0 or later

### ISSUE THREAD

**Issue by yihming** [scverse/anndata#194]
When reading an h5ad file in 'r+' backed mode:

`adata = anndata.read_h5ad(filename, 'r+')`

and then converting it to ``anndata.h5py.h5sparse.backed_csr_matrix`` using 

`X = adata.X[:]`

with scipy 1.3.0 or later, this operation emitted the following error:

```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yy939/mgh/miniconda3/envs/scCloud-test/lib/python3.7/site-packages/anndata/h5py/h5sparse.py", line 291, in \_ \_getitem\_ \_
    return mock_matrix[row, col]
  File "/Users/yy939/mgh/miniconda3/envs/scCloud-test/lib/python3.7/site-packages/scipy/sparse/_index.py", line 50, in \_ \_getitem\_ \_
    return self.copy()
  File "/Users/yy939/mgh/miniconda3/envs/scCloud-test/lib/python3.7/site-packages/scipy/sparse/data.py", line 91, in copy
    return self._with_data(self.data.copy(), copy=True)
AttributeError: 'Dataset' object has no attribute 'copy'
```

However, if I switch to scipy 1.2.1 or 1.2.2, this operation worked properly.

I checked both anndata 0.6.22.post1 and this GitHub repository version, and both of them gave me the same issue as above.

Could you please check this inconsistency? Thanks!

Sincerely,
Yiming Ynag

**Comment by yihming** [comment]
When I searched in the past issues, I found [this one](https://github.com/theislab/anndata/issues/186) which has exactly the same issue as mine.

So I redid the python script in that issue, and was able to reproduce the same error with scipy 1.3.0 or later, while it worked properly with scipy 1.2.2 or earlier.

Hope it could provide a good test case for your diagnosis.

**Comment by ivirshup** [comment]
I also noticed this, and is kinda addressed in 5dc5f4d. However, this keeps the scipy behavior of returning a copy of the sparse matrix which doesn't sound like what you want here.

**Comment by yihming** [comment]
Hi Issac,

Glad to hear that you have some solution regarding this issue. It seems that your commitment is not on master branch. Is it possible to check it out on my machine to try it on? Thanks!


Sincerely,
Yiming

**Comment by ivirshup** [comment]
Sorry for the late response on this! That commit is now on master.
