### ISSUE TITLE
ImportError: cannot import name 'ensure_df_homogeneous' from 'anndata.utils'

### ISSUE THREAD

**Issue by Minoo-ASTY** [scverse/anndata#941]
Hi,

I am using anndata package but I keep getting below error: `ImportError: cannot import name 'ensure_df_homogeneous' from 'anndata.utils'`

Amny idea how to fix this? 
I am working on python 3.9 envirnment by the way.

**Comment by ivirshup** [comment]
Can you provide a reproducible example of this, and let us know what version you're using via session_info? (e.g. `import session_info; session_info.show(html=False, dependencies=True)`

**Comment by Minoo-ASTY** [comment]
This is what I got when runing the command below:

`import pytometry as pm
`
```
import pytometry as pm
Traceback (most recent call last):

  Cell In[14], line 1
    import pytometry as pm

  File ~/opt/anaconda3/envs/py39/lib/python3.9/site-packages/pytometry/__init__.py:25
    from . import plotting as pl

  File ~/opt/anaconda3/envs/py39/lib/python3.9/site-packages/pytometry/plotting/__init__.py:1
    from ._histogram import plotdata

  File ~/opt/anaconda3/envs/py39/lib/python3.9/site-packages/pytometry/plotting/_histogram.py:5
    from anndata import AnnData

  File ~/opt/anaconda3/envs/py39/lib/python3.9/site-packages/anndata/__init__.py:1
    from ._core.anndata import AnnData, ImplicitModificationWarning

  File ~/opt/anaconda3/envs/py39/lib/python3.9/site-packages/anndata/_core/anndata.py:25
    from .raw import Raw

  File ~/opt/anaconda3/envs/py39/lib/python3.9/site-packages/anndata/_core/raw.py:11
    from .aligned_mapping import AxisArrays, AxisArraysView

  File ~/opt/anaconda3/envs/py39/lib/python3.9/site-packages/anndata/_core/aligned_mapping.py:11
    from ..utils import deprecated, ensure_df_homogeneous

ImportError: cannot import name 'ensure_df_homogeneous' from 'anndata.utils' (/Users/minooashtiani/opt/anaconda3/envs/py39/lib/python3.9/site-packages/anndata/utils.py)
```

This is the result of running the below command as you requirred:

`session_info.show(html=False, dependencies=True)
`
```
session_info.show(html=False, dependencies=True)
Traceback (most recent call last):

  Cell In[18], line 1
    session_info.show(html=False, dependencies=True)

  File ~/opt/anaconda3/envs/py39/lib/python3.9/site-packages/session_info/main.py:209 in show
    mod = sys.modules[mod_name]

KeyError: 'anndata'
```

Please let me know if anything else required from my side. Thanks in advance

**Comment by Minoo-ASTY** [comment]
@ivirshup I removed and create the envirnment again and installing the packages all again and this time I didint get any error for anndata. I guess that's solved.

**Comment by flying-sheep** [comment]
great!
