### ISSUE TITLE
AttributeError: 'DataFrameView' object has no attribute '_view_args' with Pandas 2.1.2+

### ISSUE THREAD

**Issue by Zethson** [scverse/anndata#1223]
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of anndata.
- [X] (optional) I have confirmed this bug exists on the master branch of anndata.

### Report

Started appearing in several of ehrapy's tests with 2.1.2. 

Traceback:

```pytb
ehrapy/anndata/anndata_ext.py:226: in move_to_obs
    adata.obs[num_var] = adata.obs[num_var].apply(pd.to_numeric, errors="ignore", downcast="float")
../../miniconda3/envs/ehrapy/lib/python3.11/site-packages/anndata/_core/views.py:69: in __setitem__
    if self._view_args is None:

    @final
    def __getattr__(self, name: str):
        """
        After regular attribute access, try looking up the name
        This allows simpler access to columns for interactive use.
        """
        # Note: obj.x will always call obj.__getattribute__('x') prior to
        # calling obj.__getattr__('x').
        if (
            name not in self._internal_names_set
            and name not in self._metadata
            and name not in self._accessors
            and self._info_axis._can_hold_identifiers_and_holds_name(name)
        ):
            return self[name]
>       return object.__getattribute__(self, name)
E       AttributeError: 'DataFrameView' object has no attribute '_view_args'

../../miniconda3/envs/ehrapy/lib/python3.11/site-packages/pandas/core/generic.py:6204: AttributeError
```

### Versions

Latest anndata

Pandas 2.1.2 (aka the forbidden one) and it works with 2.1.1

But it's not https://github.com/scverse/anndata/issues/1210

**Comment by flying-sheep** [comment]
I think the root cause is the same: https://github.com/pandas-dev/pandas/issues/55763

`'DataFrameView' object has no attribute '_view_args'` sounds like “`.copy` or so made a new DataFrameView when it should have made a DataFrame, and didn’t set all fields”

**Comment by ivirshup** [comment]
Would be nice to confirm if this is fixed by https://github.com/pandas-dev/pandas/pull/55764

**Comment by Zethson** [comment]
@ivirshup tested and it does indeed :) Thank you

**Comment by flying-sheep** [comment]
In that case, closing as duplicate of #1210
